### ISSUE TITLE
Add Gitlab Count (issues/MR) support

### ISSUE THREAD

**Issue by jsdidierlaurent** [monitoror/monitoror#13]
See: https://github.com/xanzy/go-gitlab

**Comment by koalalorenzo** [comment]
I hope this will be included in future releases, seeing being popped out from 1.0.0 makes me sad a little

**Comment by Alex-D** [comment]
# 4.0.0 adds GitLab support

- [Read the release note](https://github.com/monitoror/monitoror/issues/286#issuecomment-644796841)
- [4.0.0 changelog / upgrade](https://github.com/monitoror/monitoror/releases/tag/4.0.0)
- [Download & Docker](https://monitoror.com/download/)
- [GitLab monitorable documentation](https://monitoror.com/documentation/#gitlab)

----

### Support Monitoror

If you want to support our work on Monitoror, please consider donate or become a sponsor :)

- [Donate on OpenCollective](https://opencollective.com/monitoror)
- [Become a Sponsor on GitHub](https://github.com/sponsors/monitoror)
