### ISSUE TITLE
Improve config path/URL presence check and display in UI

### ISSUE THREAD

**Issue by Alex-D** [monitoror/monitoror#201]
For now, the shown error is the same when there is no config path/URL or when Core cannot load the given config, etc.

In UI, we need to add a check to distinguish an empty path/URL (and prevent calling the API) from a non-empty errored path/URL.

Depends on #191

**Comment by jsdidierlaurent** [comment]
No, if you forgot path or URL config root return 500 status with "query params errors".

If the file is missing, the error wrapped in configBag
