### ISSUE TITLE
Improve Core startup module state list by adding some explanation about why a module is disabled

### ISSUE THREAD

**Issue by Jeremy1026** [monitoror/monitoror#215]
```

./monitoror 

    __  ___            _ __
   /  |/  /___  ____  (_) /_____  _________  _____
  / /|_/ / __ \/ __ \/ / __/ __ \/ ___/ __ \/ ___/
 / /  / / /_/ / / / / / /_/ /_/ / /  / /_/ / /
/_/  /_/\____/_/ /_/_/\__/\____/_/   \____/_/ 3.1.0-dev-1583327068

https://github.com/monitoror/monitoror
_____________________________________________________

⇨ UI: enabled
⇨ PING: disabled
⇨ PORT: enabled
⇨ HTTP: enabled
⇨ PINGDOM: disabled
⇨ TRAVISCI: enabled
⇨ JENKINS: disabled
⇨ AZUREDEVOPS: disabled
⇨ GITHUB: disabled

```

Is there anything I need to do to make these be enabled?

**Comment by Alex-D** [comment]
Hey!

Yep, you need to configure things following the documentation :)

Monitoror needs to know some things to be able to enable some tile types: API endpoint, credentials, etc.

https://monitoror.com/documentation/#azure-devops

**Comment by saevarom** [comment]
I'm having an issue with PING. I've tried adding the configuration options mentioned in PING to .env but it is not enabled. I'm on Mac OS.

**Comment by Alex-D** [comment]
For Ping, it's another thing, you need to allow the app to do ping calls.

I need to test that in a mac. There is a note for linux users, but setcap does not exist on macOS ><

**Comment by Alex-D** [comment]
Dirty solution: run monitoror as root with sudo. I'm looking for a more elegant solution.

**Comment by Alex-D** [comment]
So, I've updated the documentation to make it more evident that you need to run as super-user on macOS. For Linux, there is a cleaner way, see: https://monitoror.com/documentation/#tile

**Comment by Alex-D** [comment]
```
MONITOROR x.y.z-dev
https://monitoror.com

-------------------------------------------

You are in dev mode

To see UI, run `yarn serve` in `ui` folder.
For more details, read the development guide:
https://monitoror.com/guides/#development

-------------------------------------------

Enabled modules
===============

- PORT
- AZURE
- JENKINS [default, variants: [variant1, variant2]]
    /!\ Errored configuration variant: variant3
- GITHUB
	/!\ Errored default configuration

The module you need is not listed here?
Please read the module documentation to discover all available modules and see how to enable them:
https://monitoror.com/3.0/documentation/
```

Note: the "You are in dev mode" is only shown when running Monitoror from `make run`
Note: no `/3.0` in the last URL in dev

**Comment by Alex-D** [comment]
We worked hard with @jsdidierlaurent to make the startup log more precise, with core configuration errors.

![Screenshoot of new startup logs](https://user-images.githubusercontent.com/426843/77810713-4566ed00-7096-11ea-9763-679483f75443.png)

This will come in 3.2.0
