### ISSUE TITLE
HTTP-STATUS tile returns HTML as value instead of no value

### ISSUE THREAD

**Issue by schweizerbolzonello** [monitoror/monitoror#216]
Hello,
Two issues on my side, I tried to read the documentation in all ways, apologies if I missed something.

1) When I try latest version, with configuration parameters (ex HTTP-STATUS tile) like this : https://monitoror.com/assets/demo.monitoror.com-config.json, all is ok.
However if I use https://monitoror.com/documentation/#tile-http-status and I add `statusCodeMin` or `statusCodeMax`, Monitoror complains that the file is not properly formatted.

2) On HTTP-STATUS tiles that are HTTP 200, the HTML content of the page is returned in the tile, for example: 
```json
        {
            "type": "HTTP-STATUS",
            "label": "Google",
            "params": {
                "url": "https://www.google.com",
                "status": "200"
            }
        },
```

will return :

![image](https://user-images.githubusercontent.com/5364364/75902023-14edb380-5e48-11ea-9b9e-c5759656bc62.png)

Thanks for this fantastic project and for the help

Cheers,
Thomas

**Comment by schweizerbolzonello** [comment]
Regarding n°2, if I put one HTTP-STATUS alone in a GROUP then I don't have HTML code returned (if it can help)

**Comment by Alex-D** [comment]
HTTP-STATUS has a known bug, but we through we merge the fix, buuut, no :-°

So yep, we have the fix, for the next version \o/

However, the `status` param comes from nowhere ^^ there is a `minStatusCode` and `maxStatusCode`, which should be both numbers and not strings :)

**Comment by schweizerbolzonello** [comment]
Thanks @Alex-D for the help/insights on the issue/question, appreciated!

**Comment by Japh** [comment]
I also get this issue. Using the correct status code params doesn't effect it. Looking forward to the next version to resolve the issue!

**Comment by Alex-D** [comment]
The fix will come in the next version: v3.1.0 🎉

**Comment by dotancohen81** [comment]
Hi,

This issue is still persisting on 3.1.0-dev-1583327038

**Comment by Alex-D** [comment]
Yeah we know, the 3.1.0-dev is the 3.0.0 (stable), we failed at build ^^'
