### ISSUE TITLE
Add .env detailed documentation and example

### ISSUE THREAD

**Issue by internalfx** [monitoror/monitoror#218]
Based on the following documentation...
![image](https://user-images.githubusercontent.com/583701/75906504-0f6e7a00-5e04-11ea-829f-1ada79b0dd3c.png)

I set my `.env` file as the following...

```
MO_PORT 9000
```

However it didn't work until I tried

```
MO_PORT=9000
```

I think a full example could add some clarity to the .env format.

Thanks for a great tool!

**Comment by Alex-D** [comment]
Arf, we take the standard .env format, but you right, an example is a must-have! :)

Added to the TODO 📝

**Comment by mmmpie** [comment]
The documentation for core configuration just needs to add an equals sign.
<img width="632" alt="Add__env_detailed_documentation_and_example_·_Issue__218_·_monitoror_monitoror" src="https://user-images.githubusercontent.com/326847/77957623-9b02eb80-7288-11ea-82c4-b135c32306e1.png">
