### ISSUE TITLE
Authentication for HTTP Requests

### ISSUE THREAD

**Issue by mvaldes14** [monitoror/monitoror#221]
Some endpoints may require to pass username & password, it would be nice to define those in the tile.
Due to security those can also be read from .env/environment variables.

```json
{
  "type": "HTTP-FORMATTED",
  "params": {
    "url": "http://localhost/count",
    "format": "JSON",
    "key": "sub.\"dotted.key\".[0]",
    "username": "myuser" || ${MYUSER},
    "password": "mypassword" || ${MYPASSWORD}
  }
}
```

**Comment by jsdidierlaurent** [comment]
Hey ! 

It's a good idea ! We can add user/password or maybe Bearer token in .env file and inject them in each HTTP-* tiles requests.

**Comment by Alex-D** [comment]
Maybe create some named auth profiles via .env and use them in config? Like configuration variants.

**Comment by Magorx15** [comment]
Hi! Any update on this?
