### ISSUE TITLE
Set config path/URL from `.env` + named configs

### ISSUE THREAD

**Issue by ThePadawan** [monitoror/monitoror#222]
I'm running monitoror on a machine **B**. I configured a config.json in the same folder as monitoror.

I can successfully access monitoror at http://B:8080/?configPath=./config.json, but rather than bookmark that quite complicated URL, I instead configured a reverse nginx proxy using a DNS CNAME status.example.org on my machine **A**.

I set up the reverse proxies

* https://status.example.org/ => http://B:8080/?configPath=./config.json and
* https://status.example.org/* => http://B:8080/*

I verified that the reverse proxy accesses exactly http://B:8080/?configPath=./config.json when accessing https://status.example.org/, but monitoror still tells me that I need to specify a valid configPath or configUrl.

I assume this is the case because the frontend application inspects the *current* query parameters and does not fall back to those specified when accessing / for the first time.

Accessing monitoror via https://status.example.org/?configPath=./config.json succeeds, but rather defeats the purpose of the reverse proxy in the first place.

As an alternate solution, I would love to be able to simply pin the value "config.json" server side as well (since I only run this one instance of monitoror).

**Comment by ThePadawan** [comment]
Not quite - this does a redirect to add the query parameters if they are not present. This still adds them to the user-visible address bar, which I would like to avoid.

**Comment by Alex-D** [comment]
I've talked about that with @Grafikart and we have found a simple solution: define a default configPath/URL in `.env` and another option to disable the ability to load any other config for more safety.


### Thinking about implementation

Today, UI takes the `configPath`/`configUrl`, sends it to the core via `/api/v1/config` with a query parameter.

Maybe we can allow to not give any query parameter, and the Core will respond with the default config based on `.env` option.

```
MO_DEFAULT_CONFIG_PATH=./config.json
# OR
MO_DEFAULT_CONFIG_URL=https://gist.github.com/...
```


### Merge `configPath` and `configUrl`

To make things easier, we should merge `configPath` and `configUrl` in a unique `config` parameter. This will allow us to have only one environment variable for all and one single query parameter on UI.

```
MO_DEFAULT_CONFIG=./config.json
# OR
MO_DEFAULT_CONFIG=https://gist.github.com/...
```

### Going further: named configurations

Maybe we can imagine named config in `.env`, allowing those with multiple screens to define some configuration path/URL, and then use them with a simple name: `?config=screen1`

```
MO_DEFAULT_CONFIG_SCREEN1=./config.json
MO_DEFAULT_CONFIG_SCREEN2=https://gist.github.com/...
```

Is that even possible @jsdidierlaurent?


### Detection rules

if `^./` => path
else if `^https?://` => URL
else if a named config is found in the `.env` with the same name
else => does not exist, return an error

**Comment by ThePadawan** [comment]
Being able to define a default config file would definitely solve my use case! Many thanks for considering it as a feature :)

**Comment by ThePadawan** [comment]
BTW, I also noticed that there is no restriction on using ".." in the configPath query parameter. Right now it's possible to read any json file that the user under which monitoror runs can access.

The file contents are not displayed to the user, so this isn't that great of an issue, but disallowing ".." in the path completely would still be a definitive security improvement.

**Comment by Alex-D** [comment]
In a perfect world, you should create a specific user for Monitoror with just read access to the monitoror folder or something like that. But yep, that was something that we known before the launch, plus some users has already told use since the launch, so we will work on it.

**Comment by jsdidierlaurent** [comment]
> ### Thinking about implementation
> Today, UI takes the `configPath`/`configUrl`, sends it to the core via `/api/v1/config` with a query parameter.
> 
> Maybe we can allow to not give any query parameter, and the Core will respond with the default config based on `.env` option.
> 
> ```
> MO_DEFAULT_CONFIG_PATH=./config.json
> # OR
> MO_DEFAULT_CONFIG_URL=https://gist.github.com/...
> ```

Looks good to me!

> ### Merge `configPath` and `configUrl`
> To make things easier, we should merge `configPath` and `configUrl` in a unique `config` parameter. This will allow us to have only one environment variable for all and one single query parameter on UI.
> 
> ```
> MO_DEFAULT_CONFIG=./config.json
> # OR
> MO_DEFAULT_CONFIG=https://gist.github.com/...
> ```

Same, it's pretty simple to add this :smile: 

> ### Going further: named configurations
> Maybe we can imagine named config in `.env`, allowing those with multiple screens to define some configuration path/URL, and then use them with a simple name: `?config=screen1`
> 
> ```
> MO_DEFAULT_CONFIG_SCREEN1=./config.json
> MO_DEFAULT_CONFIG_SCREEN2=https://gist.github.com/...
> ```
> 
> Is that even possible @jsdidierlaurent?

i think we can reuse "variant" logic and add something like this:
```
MO_VARIANT1_CONFIG=./config.json
MO_VARIANT2_CONFIG=https://gist.github.com/...
```

We can also continue to support ui config for override "DEFAULT" config 

/api/v1/config?config=??? can be:
- empty => use DEFAULT config variant if set
- variant => return config variant if set
- url or path

**Comment by Alex-D** [comment]
I've edit [my comment](https://github.com/monitoror/monitoror/issues/222#issuecomment-595385768) in consequence :)

**Comment by jsdidierlaurent** [comment]
Maybe disable loading config using path from UI to avoid any directory traversal attack.

**Comment by taigrr** [comment]
That last comment about directory traversal disturbs me. Has that been broken out into a separate issue somewhere else or should I create one?

**Comment by Alex-D** [comment]
As we want to catch all security issues via this refactor, we did not need a separate issue for that.

The right way to avoid any issue is to run Monitoror with a dedicated user, with the right grants. I'm working on a guide about that.

To avoid all cases when users run Monitoror with root or anything with too many rights, I think we need to lock path usage to the Core side only by default, with an env variable to unlock that maybe.
