### ISSUE TITLE
Create a Docker image

### ISSUE THREAD

**Issue by Korijn** [monitoror/monitoror#226]
Is there one or is development of one planned?

Cool project!

**Comment by jsdidierlaurent** [comment]
Hello !

It's planned! But I didn't take the time to do the pipeline to push the image on dockerhub and / or github packages.

Comming soon :smile:

**Comment by Korijn** [comment]
Thanks!

**Comment by thomasleveil** [comment]
Do you need any help with that ?

**Comment by jsdidierlaurent** [comment]
Hi,

I push monitoror docker image on docker hub: https://hub.docker.com/r/monitoror/monitoror

Readme / Documentation come later ^^
