### ISSUE TITLE
BuildKite and other CI support workaround

### ISSUE THREAD

**Issue by taitems** [monitoror/monitoror#227]
Not a true issue, but wanted to document this somewhere so it can be found via Google etc.

If you're wanting to monitor a build status in BuildKite (or perhaps any other CI framework) which is not currently supported, a temporary workaround is to use the SVG badge and regex pairing to extract the "passing" text.

For instance, this is `monitoror`'s own build badge:
![build status](https://camo.githubusercontent.com/257c3cc46db28b8d011417a9a81073c64c3c9616/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f776f726b666c6f772f7374617475732f6d6f6e69746f726f722f6d6f6e69746f726f722f636f6e74696e756f75732d696e746567726174696f6e3f7374796c653d666f722d7468652d6261646765)

Which you could monitor as:
```json
{
    "type": "HTTP-RAW",
    "label": "Build Status",
    "params": {
        "url": "https://camo.githubusercontent.com/257c3cc46db28b8d011417a9a81073c64c3c9616/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f776f726b666c6f772f7374617475732f6d6f6e69746f726f722f6d6f6e69746f726f722f636f6e74696e756f75732d696e746567726174696f6e3f7374796c653d666f722d7468652d6261646765",
        "regex": "passing"
    }
}
```

This way there's no auth, no API keys, nothing! A true testament to the versatility of this plugin!

**Comment by oviliz** [comment]
I can't get this work @taitems 
```
{
  "version": "1.0",
  "columns": 4,
  "tiles": [
    {
      "type": "HTTP-RAW",
      "label": "Build Status",
      "params": {
        "url": "https://camo.githubusercontent.com/257c3cc46db28b8d011417a9a81073c64c3c9616/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f776f726b666c6f772f7374617475732f6d6f6e69746f726f722f6d6f6e69746f726f722f636f6e74696e756f75732d696e746567726174696f6e3f7374796c653d666f722d7468652d6261646765",
        "regex": "passing"
      }
    }
  ]
}
```
![image](https://user-images.githubusercontent.com/73616/76688269-38bcb080-6623-11ea-8b24-a9377ecaa1b4.png)
It seems that I can't get any HTTP-RAW to work to be honest, but trying to use some real examples to rull out is me playing wrongly with regex.

**Comment by taitems** [comment]
@oviliz I'm not in a position to replicate this locally but looking at the source code of the build status SVG it's all uppercase, so perhaps try:
```
"regex": "PASSING"
```

**Comment by oviliz** [comment]
This works in the sense that the tile becomes green. However, it gets a whole lot of text so the trick doesn't seem usable I'm afraid.
![image](https://user-images.githubusercontent.com/73616/76705518-762f4580-66d8-11ea-9b38-d57be44ec86f.png)
