### ISSUE TITLE
Jenkins: unable to find job

### ISSUE THREAD

**Issue by dill0wn** [monitoror/monitoror#235]
Very cool monitoring tool :) Thank you!

I am trying to get the basic jenkins tile working.

I created a private api token in jenkins.

Rather than the .env approach, I have opted to create a bash script that lives next to monitoror:
```
#!/bin/bash

export MO_MONITORABLE_JENKINS_URL="https://my.jenkins.url/"
export MO_MONITORABLE_JENKINS_LOGIN="username"
export MO_MONITORABLE_JENKINS_TOKEN="*****"
monitoror
```

The server starts fine. Other tiles work fine. Jenkins does not. :(

My jenkins tile looks like this:
```
    {
      "type": "JENKINS-BUILD",
      "params": {
        "job": "myjob"
      }
    }
```

My jenkins job lives at: `https://my.jenkins.url/job/myjob` (urls and job names obscured for privacy)

I should maybe note that we're currently running Jenkins [2.138.2](https://jenkins.io/changelog-stable/#v2.138.2)(which is about 1.5 years old at this point).

Is there any way to view any logs coming from monitoror to help track down the issue?

**Comment by Alex-D** [comment]
Hey!

Did your job handle one branch? Or multiple branches? If multiple ones, please add `branch` param. If not... try to switch on the `JENKINS-MULTIBRANCH`, maybe? And see if it's better ^^

**Comment by dill0wn** [comment]
I don't _think_ it is a multiple branch job (although it might be a multiple SCM job).

I have tried specifying a branch param `master`, no dice.

I have tried multibranch with and without a `"match": "master"` and still get an error. My config looks something like this:
```
    {
      "type": "JENKINS-MULTIBRANCH",
      "params": {
        "job": "myjob"
      }
    }
```

I get a variation on the following error when attempting JENKINS-MULTIBRANCH
```
Error while listing JENKINS-MULTIBRANCH dynamic tiles (params: {"job":"myjob"}). unable to find job
ERROR_UNABLE_TO_HYDRATE 
```

My jenkins pipeline looks like this:
![Screen Shot 2020-03-06 at 11 36 35 AM](https://user-images.githubusercontent.com/1267330/76103064-0cf45780-5f9f-11ea-9d82-5b03b5dcc393.png)

**Comment by jsdidierlaurent** [comment]
Hello !

JENKINS-BUILD is used to get status of jobs like that http://your.jenkins.test/job/your-job-id

For me your first config looks good, but a wrong username / token or a wrong right on this token can cause this error

**Comment by dill0wn** [comment]
OK, I double checked my username it's accurate. I tried both my userID and my user fullname. I generated a new token and tried that. None of these cases are working :(

Are there any specific permissions I might need to enable on Jenkins?

My jenkins server is only reachable through a VPN. I am running monitoror core from my machine. My machine is connected to the VPN. My machine can connect to jenkins through the vpn. But would something like that make a difference? Nevermind, I just did a quick test. If the host is something unreachable the Tile says 'timeout' rather than 'unable to find job'.

**Comment by jsdidierlaurent** [comment]
You can test your credentials / right with:
```
# Linux / Mac
curl http://{jenkins-base-url}/job/{job-name}/api/json --user {user}:{token}
```

```
# Powershell
$Header = @{"Authorization" = "Basic "+[System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("{user}:{token}"))}
Invoke-RestMethod -Method GET -Header $Header -uri "{jenkins-base-url}/job/{job-name}/api/json"
```

**Comment by dill0wn** [comment]
OK, I'm unable to get an authorized response. This seems to be an issue with my credentials and/or server setup. Closing for now.
