### ISSUE TITLE
ping: resolve hostname with wins failes

### ISSUE THREAD

**Issue by mrothenbuecher** [monitoror/monitoror#250]
Hi there,

if I use a ping tile with the IP of a host everything works fine. If I use the the name of this server (Windows Machine, resolve via wins) the same tile won't work.
If I ping manually from the console with the hostname it works also fine.

**Comment by jsdidierlaurent** [comment]
Hi,

Monitoror use https://github.com/sparrc/go-ping to perform a ping. 
This library uses system DNS configuration to resolve a domain name.

If you try with monitoror.com does it work?

**Comment by mrothenbuecher** [comment]
> If you try with monitoror.com does it work?

Yes this works.

**Comment by mrothenbuecher** [comment]
The bug seams only to appear on a linux machine, on my windows pc the same config works fine.

**Comment by Alex-D** [comment]
Since there is no code difference between OS on ping, the issue is on your side.
We can't help you, sorry ^^
