### ISSUE TITLE
Add ability to set a custom job label to multi-branch jobs

### ISSUE THREAD

**Issue by jutenga** [monitoror/monitoror#252]
Hello !

First, I would like to thank the team for this wonderful project.

When I define a `JENKINS-MULTIBRANCH` and my job name is very long, Is it possible to alias it ?
On one column, it's fine.
When there is more columns, it become unreadable
Example : 

```json
{
    "type": "JENKINS-MULTIBRANCH",
    "label": "feature",
    "params": {
        "job": "BRANCH-PHP/job/MY-PROJECT-NAME/job/DEVEVELOPMENT/job/GIT-BRANCH-BUILD",
        "match": "feature"
    }
}
```

Before : 

![Monitoror](https://user-images.githubusercontent.com/1016467/76300600-44277900-62bd-11ea-88f6-6894f392f7d5.png)

After : 

```json
{
    "type": "JENKINS-MULTIBRANCH",
    "label": "feature",
    "params": {
        "job": "BRANCH-PHP/job/MY-PROJECT-NAME/job/DEVEVELOPMENT/job/GIT-BRANCH-BUILD",
        "match": "feature",
        "label": "GitBranchBuild"
    }
}
```

![Monitoror_suggestion](https://user-images.githubusercontent.com/1016467/76300611-4be71d80-62bd-11ea-8842-38c794d2bd1c.png)

Thank's for reading !

FYI : I use chrome with the dark reader extension

**Comment by Alex-D** [comment]
Hey!

Maybe the key should be named something like "jobLabel" or something like that to avoid confusion with tile label.

I think it is easy to do that!

@jsdidierlaurent, what did you think about adding this to the 3.2 release ?

**Comment by jsdidierlaurent** [comment]
Ok for "jobLabel" i will add this in 3.2 :+1:

**Comment by jutenga** [comment]
As someone says : "You're breathtaking !!!".

**Comment by jsdidierlaurent** [comment]
Forwarding label of metatile (like JENKINS-MULTIBRANCH)  to every subtile will be ok for you ?

like: ```
{
    "type": "JENKINS-MULTIBRANCH",
    "label": "GitBranchBuild",
    "params": {
        "job": "BRANCH-PHP/job/MY-PROJECT-NAME/job/DEVEVELOPMENT/job/GIT-BRANCH-BUILD",
        "match": "feature"
    }
}
```

**Comment by jutenga** [comment]
It wiil be ok for me !
Thank's for your work !
