### ISSUE TITLE
How to bind $PORT of Heroku when deploy with Docker

### ISSUE THREAD

**Issue by qinyuanpei** [monitoror/monitoror#256]
I am going to deploy Monitoror on Heroku. At first, I deploy it on my own machine with Docker. 
I bind 9090 to 8080 of Docker, and it works well. But I am confused to deploy it on Heroku with the $PORT。The following is my Dockerfile：
```
FROM monitoror/monitoror:latest
ENV MONITOROR_VERSION=3.1.0
ENV MO_PORT=8080
ENV PORT=8080
CMD "/bin/monitoror"
```
Can you kindly help me to solve this problem?

**Comment by jsdidierlaurent** [comment]
Hello,

I don't really know Heroku, but from memory you have to use $ PORT in the Dockerfile right?

Something like that?

```
FROM monitoror/monitoror:3.1.0
ENV MONITOROR_VERSION=3.1.0
ENV MO_PORT=$PORT
CMD "/bin/monitoror"
```
