### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by craigcpaterson** [monitoror/monitoror#262]
Hi,
It would be helpful if you could add how to uninstall the app for macOS and other platforms. I would like to remove Monitoror as it is conflicting with other http services I need to use and it would be great to have the documentation on how to do this properly.
Thank you.

**Comment by jsdidierlaurent** [comment]
There is no installation process for monitoror, it's just binary file to run. If you want to "uninstall" monitoror you have to remove this binary file and it's done.

Btw, if monitoror conflic with other web app, you can change service Port with another one using MO_PORT=12345 in .env file.
