### ISSUE TITLE
support for yaml config files

### ISSUE THREAD

**Issue by thomasleveil** [monitoror/monitoror#267]
Would you consider supporting config files in yaml format ?

This would allow us to use comments in the config files as well as profit from achors/aliases

**Comment by Alex-D** [comment]
I don't think so, but we can improve things!

Having two configuration formats means more documentation and inconsistency between configurations.

I will take the issue in another way:

- why did you need comments?
- why did you need YAML specific features as anchors and alias?

I need concrete use cases to justify such significant work like that.

In conclusion, isn't YAML overkill?

**Comment by thomasleveil** [comment]
Why comments ?

When your config file grows big, and has to be maintained by a team, it
would be very useful to add comments. Comments can justify why things are
done a certain way that might feel weird to newcomers. Give guidelines, etc.

Why yaml anchors/alias ?

For Dont Repeat Yourself. i ended up repeating the same tiles quite a lot
in my first config file since I have the same things to check on multiple
servers. Yaml anchors could have been handy.

Finally, a yaml document can be expressed in json. So support for this
format can be implemented as a transformation into json, and the generated
json can feed the existing implementation without any change


Le ven. 13 mars 2020 à 00:16, Alexandre Demode <notifications@github.com> a
écrit :

**Comment by Alex-D** [comment]
As I said, implementation is not the question, and it's easy to do.

The cost is to maintain documentation of two formats.

Comments can be added to JSON if we want, I think. So the only remaining point is anchors.

We will take a look at that with @jsdidierlaurent

**Comment by Alex-D** [comment]
After a short discussion with @jsdidierlaurent, we will not add YAML support. The gain is low, YAML is for power users, and Monitoror is not only for them.

We will add a way to add comments to the JSON, more like notes than comments via a `note` field to stick to the JSON 1 standard.

**Comment by taigrr** [comment]
Actually @Alex-D I recommend you [take a look at viper](https://github.com/spf13/viper) which is an industry-standard tool for parsing and writing out config files of all formats, with no extra work to support many formats. I've used it extensively and it's a fantastic package :)

**Comment by Alex-D** [comment]
This is not a technical issue. We already use viper.

The issue is: we need to write and maintain documentation for JSON *AND* YAML... + Consider all beginners who will have problems with YAML.

For now, we did not have time/energy to put in that.

If you want to use YAML, feel free to parse it to JSON :)

**Comment by taigrr** [comment]
Ah, documentation is the issue. Got it. Totally makes sense.
