### ISSUE TITLE
allow to disable SSL validation for HTTP requests

### ISSUE THREAD

**Issue by thomasleveil** [monitoror/monitoror#268]
I would like to monitor some https URL which presents a self-signed certificate.

- Could a tile parameter be added to disable SSL validation
- Could a custom CA root certificate be specified to validate SSL cert presented by the https servers ?

**Comment by thomasleveil** [comment]
let me answer my own question :P

We can set `MO_MONITORABLE_HTTP_SSLVERIFY=false`  in the `.env` file.

**Comment by Alex-D** [comment]
And custom CA must be installed on system level :)

**Comment by thomasleveil** [comment]
Could you give pointers on which golang HTTP client is used to figure out
on its documentation where on the system it will look for trusted ca root
bundles?

I'm quite unfamiliar with go, and in my experience with other languages,
not all http client libs relly on the system trusted ca bundle.

Le ven. 13 mars 2020 à 00:08, Alexandre Demode <notifications@github.com> a
écrit :

**Comment by Alex-D** [comment]
No lib is used, it's embed in Go like standard library in Java.
