### ISSUE TITLE
Azure DevOps Build branch not working

### ISSUE THREAD

**Issue by oviliz** [monitoror/monitoror#271]
The Azure DevOps Build Build branch, https://monitoror.com/documentation/#tile-azuredevops-build, doesn't work. Works fine without branch when it defaults to the last build.

This is my tile:
```json
    {
      "type": "AZUREDEVOPS-BUILD",
      "label": "Infra",
      "params": {
        "project": "Project",
        "definition": 191,
        "branch": "master"
      }
    },
```

Using the latest monitoror version. Thoughts?

**Comment by jsdidierlaurent** [comment]
Hello!

Actually, Azure want branch name in `reafs/name/master` format.
I think it should be added automatically if it is not there.

**Comment by oviliz** [comment]
That works @jsdidierlaurent , thank you.
