### ISSUE TITLE
CSS enhancements: word-break and viewport width font-size

### ISSUE THREAD

**Issue by oviliz** [monitoror/monitoror#277]
Would be great to labels with "long words to be able to break and wrap onto the next line"

Would you guys also consider responsible text size set via `vw` units?

Thank you.

**Comment by Alex-D** [comment]
1. The issue is not with a long label, but long words, so yep I will fix that with `  word-break: break-word;`

2. Nope. I need to work on `zoom` auto-compute when not set. Because using viewport related unit will break things or need more work.
