### ISSUE TITLE
HTTP Status for list of urls

### ISSUE THREAD

**Issue by huynhsontung** [monitoror/monitoror#278]
Proposal for HTTP Status tile to support a list of URLs. The tile should cycle through the list repeatedly until an error appear, then change its appearance to `ERROR` or `WARNING` and show which URL is giving the error. It should keep retrying that URL until the error is clear, then back to its normal routine of repeatedly cycling through URL list.

**Comment by Alex-D** [comment]
You can already do that with a `GROUP` of `HTTP-STATUS`.

I do not think to add a multiple§URL check since we have this solution :)

Is this solution OK for you?

**Comment by huynhsontung** [comment]
I just reread the doc and that is exactly what I am looking for. Thank you! 👍
