### ISSUE TITLE
Struggling with regex - capture version or any text

### ISSUE THREAD

**Issue by oviliz** [monitoror/monitoror#279]
Hi guys, is there a way I can capture the version from this example App Store page?
https://apps.apple.com/gb/app/my-english-literature-gcse/id1335737542
![image](https://user-images.githubusercontent.com/73616/76964457-afef8e80-691a-11ea-8ff6-1d60ea23a57e.png)

I've used the example at https://monitoror.com/documentation/#tile-http-raw and amended to (just capitalized the V and removed the `:`:
```
{
  "type": "HTTP-RAW",
  "params": {
    "url": "https://apps.apple.com/gb/app/my-english-literature-gcse/id1335737542",
    "regex": "Version\s*([^\s]*)"
  }
}
```
But is not happy: "Your configuration cannot be parsed, please verify it".

I have played around regex for a few days now, referring to https://golang.org/s/re2syntax as recommended in the documentation, but I'm not getting anywhere to be honest.

**Comment by Alex-D** [comment]
Duplicates #249

**Comment by Alex-D** [comment]
To be more clear: Your issue is the same than #249: you did not escape backslashes.

Try `"regex": "Version\\s*([^\\s]*)"`

**Comment by oviliz** [comment]
Thanks @Alex-D . Escaping does not fail the configuration, however, doesn't produce a great result:
![image](https://user-images.githubusercontent.com/73616/76990022-3322db80-693f-11ea-95b1-3fbcf010c0b8.png)
Any thoughts?
```
    {
      "type": "HTTP-RAW",
      "params": {
        "url": "https://apps.apple.com/gb/app/my-english-literature-gcse/id1335737542",
        "regex": "Version\\s*([^\\s]*)"
      }
    }
```

**Comment by Alex-D** [comment]
view-source:https://apps.apple.com/gb/app/my-english-literature-gcse/id1335737542

There is a match before the one you want ^^'

Since you are trying to parse HTML, be more specific, try this:

```json
{
  "type": "HTTP-RAW",
  "params": {
    "url": "https://apps.apple.com/gb/app/my-english-literature-gcse/id1335737542",
    "regex": ">Version\\s*([\\.\\d]*)<"
  }
}
```

**Comment by oviliz** [comment]
Thank you very much @Alex-D , that works. I don't pretend to understand how it does it yet but will try my best.
Do you mind sharing another example on how to scrape the version from the next line of a text like on https://play.google.com/store/apps/details?id=com.m360.android&hl=en_GB?
![image](https://user-images.githubusercontent.com/73616/77017662-eeb13300-6972-11ea-9b30-e4136eb361ad.png)
Will try to compare the two solutions for two different use cases and understand more about how it works.

**Comment by Alex-D** [comment]
1. Open the HTML
2. check what you want to catch
3. do the regex

**Comment by oviliz** [comment]
@Alex-D , it took me a while (I'm thick) but I've got it:
`"regex": ">Current Version</div><span class=\"htlgb\"><div class=\"IQ1z0d\"><span class=\"htlgb\">*([\\.\\d]*)<"`

I guess there would have been a better way, something like `Version\n([\.\d]){5}`, but c'est la vie. :)

If someone comes across this, https://regex101.com/ is a helpful tool (see the Golang flavour).

**Comment by oviliz** [comment]
`Current Version\n*([.\d]*)` if would have been plain text.
