### ISSUE TITLE
Add the possibility to have several keys/values checked for one HTTP-FORMATTED tile

### ISSUE THREAD

**Issue by bolinocroustibat** [monitoror/monitoror#283]
I'm thinking about something like:
```json
{
    "type": "HTTP-FORMATTED",
    "params": {
        "url": "http://localhost/count",
        "format": "JSON",
        "keys": [
            {"key": "celery", "regex": "offline"},
            {"key": "S3", "regex": "offline"}
        ]
    }
}
```

This could be checked with one simple HTTP request.

**Comment by Alex-D** [comment]
Monitoror Core has cache. So if you create 10 tiles with the same URL and different checks, it will only request the URL a single time.

Please use a group with as many HTTP formatted tiles as you want :)

**Comment by bolinocroustibat** [comment]
Good to know. That's actually what I did but didn't know it was using only one request. Thanks

**Comment by bolinocroustibat** [comment]
> Monitoror Core has cache. So if you create 10 tiles with the same URL and different checks, it will only request the URL a single time.
> 
> Please use a group with as many HTTP formatted tiles as you want :)

Good to know. That's actually what I did but didn't know it was using only one request. Thanks
