### ISSUE TITLE
More examples of JSON parsing

### ISSUE THREAD

**Issue by 0x8000-0000** [monitoror/monitoror#295]
Could we have a couple more examples of JSON parsing? I am trying to parse something like:

```json
{"Load":[0.0,0.0,0.0],"Uptime":39099.01411128044}
```

or:

```json
{"status":"Idle"}
```

or:

```json
{"id":"91","since":1585668682.4,"status":"Running","task":"preintegration"}
```

I have tried all sorts of keys... such as

```json
"format": "JSON",
"key": "status"
```

but all I'm getting is "unable to lookup for key ".status" "

I'm running monitoror 3.1.0, if it helps.

Thank you!

**Comment by 0x8000-0000** [comment]
More attempts:

```
unable to lookup for key "sub."status".[0]"
unable to lookup for key "sub.".status".[0]"
unable to lookup for key ""status".[0]"
unable to lookup for key "status.[0]"
```

**Comment by jsdidierlaurent** [comment]
Hello!

Can i have your exact configuration and output?

I just try this for test:
#### config.json
```json
{
	"version":"1.0",
	"columns": 1,
	"tiles": [
		{"type": "HTTP-FORMATTED", "params": {"format": "JSON", "key": ".status", "url": "https://gist.githubusercontent.com/jsdidierlaurent/50fce7266d40e37ff03b3032ddc03f69/raw/602e64a4fc50c1f5c5012010b00e737305949730/test.json"}}
	]
}
```

#### Output expose with gist
```json
{"id":"91","since":1585668682.4,"status":"Running","task":"preintegration"}
```

#### Result
![Capture](https://user-images.githubusercontent.com/11354381/78067390-f28f7d00-7396-11ea-9fe0-d61da0933b2b.PNG)

**Comment by 0x8000-0000** [comment]
Hi Jean-Sébastien,

While preparing the answer, I have found the problem - there was a typo in my URL which was getting a "similar" JSON from a different web server than expected.

My monitor works now - thank you for responding.
