### ISSUE TITLE
Fix ui path with route prefix

### ISSUE THREAD

**Issue by chayakornjj** [monitoror/monitoror#300]
Hi, currently we have an issue eg.

Normally when we request to Monitoror we using something like 
http://localhost:8080/?configPath=./config.json

Is there any possible way that we can set up a route prefix? eg
http://localhost:8080/test-prefix/?configPath=./config.json

Thank you.

**Comment by Alex-D** [comment]
What's the usecase?

**Comment by chayakornjj** [comment]
Currently, we have internal infrastructure that defines by a prefix.
We host integration environment on something like 
`https://int.development.internal/service1`
`https://int.development.internal/service2`

And we found that this monitoring tool can help us on monitoring our service. 
It will be something like `https://int.development.internal/monitoring/?configPath=./config.json` 

But we try a lot of ways to use it with this route prefix eg. reverse proxy but no luck.

Would be possible or any suggestion for us on this?

**Comment by jsdidierlaurent** [comment]
Hello!

After a simple test with Nginx: 
```
  location /monitoror/ {
    proxy_pass http://localhost:8080/;
  }
```

Monitoror UI try to load assets in / and not /monitoror/.
We will fix this for the next release ^^

**Comment by chayakornjj** [comment]
> Hello!
> 
> After a simple test with Nginx:
> 
> ```
>   location /monitoror/ {
>     proxy_pass http://localhost:8080/;
>   }
> ```
> 
> Monitoror UI try to load assets in / and not /monitoror/.
> We will fix this for the next release ^^

That exactly what we met, We can get Monitoror page but it load assets in / without prefix

Thank you for adding this to the next release.
great job guys!

**Comment by not-ajay** [comment]
Hi @chayakornjj , Were you able to implement this ?
I want to try this without nginx and with source code changes only, any ideas ? 
Created (https://github.com/monitoror/monitoror/issues/417) for same.
