### ISSUE TITLE
Authentication for UI

### ISSUE THREAD

**Issue by lazymuggle1** [monitoror/monitoror#306]
I need to use Monitoror on the public Internet, and suggest adding the Basic Authentication configuration to the .env file:.

    MO_BASIC_AUTH_USERNAME=monitor
    MO_BASIC_AUTH_PASSWORD=mypassword
    
Then the browser will prompts for a username and password when requesting http://my.monitororsite.com/?configPath=config.json to prevent illegal access.

**Comment by taigrr** [comment]
@lazymuggle1 I would highly recommend you don't rely on the application itself to authenticate, as there are much better (security vetted, more efficient, etc) tools for doing so.

My recommendation for this is to [use nginx as a reverse proxy](https://www.linode.com/docs/web-servers/nginx/use-nginx-reverse-proxy/) instead.

[Here is a docker container instead](https://github.com/dtan4/nginx-basic-auth-proxy) if you'd rather not install and configure nginx yourself.

**Comment by lazymuggle1** [comment]
Thank you very much @taigrr.

The method you provide can work, but my suggestion is to make it as easy as possible for the end user to run the Monitoror.

**Comment by jsdidierlaurent** [comment]
Hello!

Security is very complicated and probably endless (SSL, Auth, etc) 
I prefer let expert people take care of it rather than rather than doing it wrong.

Maybe we can add "Tutorial" to explain how you can setup nginx for SSL and auth in documentation.

Maybe @Alex-D have other point of view?

**Comment by Alex-D** [comment]
Hey!

We will not implement that. Please use a reverse proxy in front of Monitoror to do so :)

**Comment by taigrr** [comment]
@Alex-D @jsdidierlaurent I am happy to write this up if you can point me to sample documentation to mimic.
