### ISSUE TITLE
Add ListenAddress Option to restrict serving

### ISSUE THREAD

**Issue by taigrr** [monitoror/monitoror#307]
Many applications allow you to restrict the listenaddress to a specific string, i.e. localhost, mydomain.com, 0.0.0.0, etc. This lets you listen on only one interface, only respond to requests coming from a specific domain, etc. and it is very helpful. For example, it would be supremely useful for #306 , as it would let you run it securely on the host.

If this option is already available, then perhaps this issue is related to #218 , and the variable name just needs to be documented. However, I dug through the code looking for it, and looking at [these lines here](https://github.com/monitoror/monitoror/blob/5a120dd5bb662c50591d649a44f02c10e00c1eb6/service/server.go#L57) it seems monitoror does autodetection to listen on all interfaces.

Would you be willing to make that the default behavior, and allow users to override it in the .env to restrict the listening address?

**Comment by lazymuggle1** [comment]
+1

**Comment by jsdidierlaurent** [comment]
Hello!

It is not possible at the moment, but it seems interesting and very easy to set up.

I will add this soon ^^
