### ISSUE TITLE
Github - PRs - 'unable to find ref checks'

### ISSUE THREAD

**Issue by mbwhite** [monitoror/monitoror#309]
Monitoror v 3.1.0

Github PR tile
```
    {
      "type": "GITHUB-PULLREQUESTS",
      "params": {
        "owner": "hyperledger",
        "repository": "fabric-chaincode-node",
        "ref": "master"
      }
```

There are (currently) 4 tiles for the PRs, but all labeled with `unable to find ref checks`
Not quite sure what this means?

Are there any debug logs I can check?

**Comment by Alex-D** [comment]
Did you have some build on branches? That's what GitHub calls "Checks". If not, we did not have anything to show.
Maybe you just want to show the PR list, without any check status?

**Comment by mbwhite** [comment]
There are build on the press, though some of the builds have completed.

**Comment by jsdidierlaurent** [comment]
I'm working on it! It's when PR come from fork ^^

I will fix this soon ^^

**Comment by mbwhite** [comment]
@jsdidierlaurent yes all these PRs are from a fork :-) 

Let me know if there's anything I do to help.. test etc.
