### ISSUE TITLE
Ping intervals ?

### ISSUE THREAD

**Issue by amarc** [monitoror/monitoror#322]
Hello, just found out Monitoror, great tool and thank you : )

Looking at example .env from this repo I just copy/pasted these 4 as I will only be monitoring ports and ping's 

MO_MONITORABLE_PING_COUNT=2
MO_MONITORABLE_PING_TIMEOUT=1000
MO_MONITORABLE_PING_INTERVAL=100

MO_MONITORABLE_PORT_TIMEOUT=2000

My question is: PING_TIMEOUT is 1 second (1000ms) ? Because testing out and dropping  outgoing ping seems to delay status change to Red for about 5 seconds not 2. 

Not that it matters too much but in production I would like to have control and sense how to configure this.

Any explanation is welcome.. 
Thanks

**Comment by Alex-D** [comment]
Ping tile allows you to get an average ping value through n calls. Like the real ping command. That's the COUNT part: you can choose how many pings will be done before returning the result.

Then, you can define how much time to wait before making the next ping call: that's the INTERVAL.

There is some TODO in docs for that ^^'

https://github.com/monitoror/monitoror/blob/ed951340a926dba0103503a109bda70ca0604cf3/docs/documentation/index.html#L1639-L1644

The timeout is a global timeout: if the N calls are not done at the TIMEOUT value, Monitoror ignores the result and consider that as an error.

**Comment by amarc** [comment]
Thank you very much. It's clearer now.

I guess logical question (and maybe should be 1st one) is at what intervals tiles/browser refreshes results? As I said, when I completely drop connection to Port X, seems tile goes RED in about 5 seconds.. sometimes it 3,4..

Thanks

**Comment by Alex-D** [comment]
The UI refresh each 10 seconds, with an initial random delay allowing us to spread request in time instead of requiring all tiles each 10 seconds at the same time.
