### ISSUE TITLE
How to use 'status' option?

### ISSUE THREAD

**Issue by loderunner84** [monitoror/monitoror#342]

**Comment by jsdidierlaurent** [comment]
Hello !

What 'status' are you talking about?

**Comment by loderunner84** [comment]
For exmple `{ "type": "HTTP-FORMATTED", "label": "Active users", "params": { "format": "JSON", "url": "https://analytics.example.com/active-users", "key": ".count", "status": "SUCCESS", "valueValues": ["0.1337"], "valueUnit": "RATIO" } },` What is mean "status" here? Changing this option has no effect for me. Tile color has not changed.

**Comment by Alex-D** [comment]
You're looking at the demo JSON, which is for... demo purpose, so we use the `faker` mode of Monitoror to display things exactly as we want.

You should not use that in `production` mode.

**Comment by loderunner84** [comment]
It not used for production, but for understanding. Can I use "status" or not? How to get "error" tile if HTTP-FORMATTED check return any "wrong" data? Can I attach status to tile params at server side?

**Comment by Alex-D** [comment]
It's a feature for Monitoror development and demo purposes, which is not shipped in the production build of Monitoror.

To be clear, this parameter does not exist in the public build of Monitoror and you should not worry about it.

Anything you need to know about HTTP-FORMATTED is in the documentation here: https://monitoror.com/documentation/#tile-http-formatted

**Comment by Alex-D** [comment]
Your config should be more like that: 

```json
{
  "type": "HTTP-FORMATTED",
  "label": "Active users",
  "params": {
    "format": "JSON",
    "url": "https://analytics.example.com/active-users",
    "key": ".count"
  }
}
```

and it will show you a green tile if the URL is reachable, or become red if it gets a 400+ HTTP status code.

**Comment by loderunner84** [comment]
Thank you it's clear now.
