### ISSUE TITLE
Docker release for v4.0.0 doesn't work

### ISSUE THREAD

**Issue by arthur-leclerc** [monitoror/monitoror#358]
Hi,

It seems that the latest version `4.0.0` does not work on Docker. I have the feeling that your binaries are not static and make use of the libc for example.

As your base image is a `scratch`, it does not contain any libs and trying to run your image gives the following output:

```
$ docker run -p 8080:8080 monitoror/monitoror:4.0.0
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

Downloading your binary show it:

```
$ ldd monitoror-linux-amd64-4.0.0
	linux-vdso.so.1 (0x00007ffe35f1e000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9ab5b7b000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f9ab57d0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9ab5d99000)
```

I'm not a Go expert, but telling Go to use the go compiler rather than the cgo compiler `CGO_ENABLED=0` and using the `-a` flag to rebuild all dependencies allowed me to have a static binary running on `scratch`. (https://github.com/monitoror/monitoror/blob/develop/scripts/build.sh#L58)

```
$ ldd monitoror-linux-amd64-4.0.0-dev
	not a dynamic executable
```

Trying the new image:

```
$ docker run -p 8080:8080 coteaz/monitoror:4.0.0-dev
```

**Comment by jsdidierlaurent** [comment]
Hi!
I totally forgot this flag when I refactor the build scripts ... my bad 😢
See: https://github.com/monitoror/monitoror/blob/0424c48df58c68ef8b5febd7aba506d18e04a894/scripts/build/build#L43

I fixed the build on develop and I already push the fix on dockerhub.

Thanks a lot for this report 😉

**Comment by arthur-leclerc** [comment]
Thanks, no problems with the new image. 👍
