### ISSUE TITLE
Generate Github PR Timeout or host unreachable

### ISSUE THREAD

**Issue by stephenway** [monitoror/monitoror#376]
Thought I'd open this issue because I've been seeing this "ERROR_UNABLE_TO_HYDRATE" error with "Timeout or host unreachable" off and on for a few weeks now and was wondering if anyone else thinks it has something to do with github rate limiting and if there is a better config with less requests or what might be causing this in general.

**Comment by jsdidierlaurent** [comment]
Hello !

Github's rate limit was a big concern. To reduce issue with rate limite, you can use different github account or set [MO_UPSTREAMCACHEEXPIRATION](https://monitoror.com/documentation/#core-cache) to a longer period.
