### ISSUE TITLE
Trying to put monitoror behind haproxy - Monitoror Core seems down

### ISSUE THREAD

**Issue by xoraingroup** [monitoror/monitoror#381]
Trying to put monitoror behind haproxy and every time i get monitoror screen with 

![image](https://user-images.githubusercontent.com/17129052/99180895-f825b180-2732-11eb-9e2b-84077ea33d4b.png)

monitoror is hosted in a vps with valid wildcard https certificate  of our domain.

Can any body help?

Thanks

**Comment by Alex-D** [comment]
Hey: 
Can you try with a light HTTP server and try to access it? If you can't, it's an issue in your setup. If you can, maybe there is something wrong with Monitoror Core.

Without more details, I close this issue. Feel free to add some details if that can help.
