### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by plegrand1** [monitoror/monitoror#385]
Hello, I just discovered your application and I wanted to know if it was possible to choose the layout of the tiles. 
For example:  
tiles 1, 2, 3 in the first column
tiles 4, 5, 6 in the second etc...
Thanks for your help

**Comment by Alex-D** [comment]
You just need to create your tiles like 1, 4, 2, 5, 3, 6, and set the column count to 2 :)

**Comment by plegrand1** [comment]
And if i use 7 column ?   ;-)

**Comment by Alex-D** [comment]
Same but set the column count to 7... I don't understand your problem ^^'
