### ISSUE TITLE
Client certificates support

### ISSUE THREAD

**Issue by apolegoshko** [monitoror/monitoror#390]
Sometimes, we need to query (HTTP-RAW tile) endpoints secured with client certificates. Could you please confirm that currently this tool **doesn't** support it ?

**Comment by jsdidierlaurent** [comment]
Hello !

You can disable ssl check with `MO_MONITORABLE_HTTP_SSLVERIFY=false`. See : https://monitoror.com/documentation/#http

Btw, But if you use self signed certificate, you can install your self signed CA Root in your system

**Comment by apolegoshko** [comment]
@jsdidierlaurent hey, I'm talking about client certificates, with disabling ssl check, the connection will not be established.

**Comment by ramkumarkb** [comment]
@jsdidierlaurent - Many APIs now a days are protected by [mTLS](https://developers.cloudflare.com/cloudflare-one/identity/devices/mutual-tls-authentication) - and requires clients to present a Client Certificate as part of the TLS handshake.

@apolegoshko - One work around you could try is to proxy the request via [Ghostunnel](https://github.com/ghostunnel/ghostunnel) and monitor Ghostunnel also (it has a health endpoint over http). 

I think this issue should not be closed but re-opened.

**Comment by apolegoshko** [comment]
Hey there. Assuming it's re opened for the future development. Is it correct ?

**Comment by agebhar1** [comment]
From the [Go documentation](https://go.dev/src/crypto/x509/root_linux.go) for Linux the certificates are picked up from these directories:
```go
// Possible directories with certificate files; all will be read.
var certDirectories = []string{
	"/etc/ssl/certs",               // SLES10/SLES11, https://golang.org/issue/12139
	"/etc/pki/tls/certs",           // Fedora/RHEL
	"/system/etc/security/cacerts", // Android
```
put the client certificates to the directories should help. If you run **monitoror** from container image you can mount the required certificates easily from your host system.
