### ISSUE TITLE
Docker container ping (docker container UUID, IP and port)

### ISSUE THREAD

**Issue by MrYoogoMusic** [monitoror/monitoror#392]
Hi,

Can you add the posibility to ping and port a docker countainer, ip and port from the pterodactyl panel and wings ? [https://pterodactyl.io/](https://pterodactyl.io/)

![image](https://user-images.githubusercontent.com/426843/111925327-b2924000-8aa8-11eb-935a-02162851e570.png)

**Comment by MrYoogoMusic** [comment]
file:///home/mryoogomusic/Images/Capture%20d%E2%80%99%C3%A9cran%20du%202021-03-21%2021-06-14.png

**Comment by Alex-D** [comment]
What do you want exactly? You already can add a PING tile with the server IP, and as many as you want PORT tiles to check all your services. Did I miss something?

**Comment by MrYoogoMusic** [comment]
What I wanted to say is that I have a minecraft server with port 25565 and I would like to have the ping of this server except that the panel does not manage to retrieve the ping (it displays 0 ms) and that this minecraft server is in a docker container.
we should be able to ping a docker container I think otherwise the server will never be able to recover the ping

**Comment by MrYoogoMusic** [comment]
I just did a test since the server is in a docker container even when turned off, it cannot find the status of the server (ON or OFF)
![BungeeCord](https://user-images.githubusercontent.com/38286695/111980695-f5830080-8b06-11eb-9bd8-bbb0d3d2264b.png)
![Capture d’écran du 2021-03-22 11-33-14](https://user-images.githubusercontent.com/38286695/111980709-fa47b480-8b06-11eb-8cbe-d407affe8b75.png)

**Comment by MrYoogoMusic** [comment]
Or it's possible to speak on discord (in french) ? MrYoogoMusic#7574

**Comment by Alex-D** [comment]
Try PORT tile instead of PING, you want to check that the service is up, not that the docker container is up.

You cannot ping a container because its IP is not on the same network. So, just check if something is listening on the wanted port, and you will be good :)

**Comment by MrYoogoMusic** [comment]
It's okay it shows me the status of my servers (on or off) on the other hand I try to ping my website and it takes 0 ms, is that normal?

**Comment by MrYoogoMusic** [comment]
And it's possible to add monitoror to a systemctl ?

**Comment by Alex-D** [comment]
Is the website hosted on the same server as Monitoror? If yes, 0ms is normal since the ping is under a millisecond on the localhost loopback.

**Comment by MrYoogoMusic** [comment]
no he is not hosted on the same server

**Comment by Alex-D** [comment]
In most cases, you must use PORT, not PING. IF you want to check if your website is up, make a PORT check on 443 (if HTTPS) or 80 (if HTTP).
