### ISSUE TITLE
Cant keep connection

### ISSUE THREAD

**Issue by AncientVipers** [monitoror/monitoror#407]
Hello,

Im running Monitoror on 192.168.1.164:8080 (Windows machine) 
Im also running a PiHole on 192.168.1.240
Im also running a Reversed Proxy Manager on 192.168.1.242.

The issue is:

![image](https://user-images.githubusercontent.com/94783201/157999391-cede867f-c11a-41f7-8412-69e3a576eb0f.png)
Monitoror says its down, but, when i refresh the page, its back online. 
![image](https://user-images.githubusercontent.com/94783201/157999418-f7f64023-62c3-4b77-a540-38dc47f616cc.png)

But after some time it just disconnects.. again...

My PC has its DNS to 192.168.1.240 (PiHole)
In the PiHole i made an DNS Record (A) pointing monitor-uptime.local to 192.168.1.242
On the Reversed Proxy manager, it listens for monitor-uptime.local and forwards it to 192.168.1.164:8080 which is the Monitoror. 

Any ideas.. or fixes?

**Comment by AncientVipers** [comment]
Any idea?

**Comment by Alex-D** [comment]
This error comes from the non-ability of the UI to fetch the configuration from the Core.
Can you check in the _Network_ pannel of your browser what is happening? Can you paste the HTTP response (or error) here?
