### ISSUE TITLE
Is the project depraceted?

### ISSUE THREAD

**Issue by melihme** [monitoror/monitoror#410]
The last commit is from 2020, but I haven't found any deprecation announcement. What is the current status of the project?

**Comment by Alex-D** [comment]
Not at all. We have some features in dev (and work on other projects).
Since there is no major issue, we do not need to fix anything ^^

We need to find some time to work on this side project.

And since there are not many donations, we can't take any day off to work on Monitoror :/

**Comment by melihme** [comment]
Thank you for your prompt answer. It is nice to hear that project is still alive.
