### ISSUE TITLE
Add API URL to each config tile

### ISSUE THREAD

**Issue by Alex-D** [monitoror/monitoror#48]
To keep server things on server side, sending API URLs via the config file seems to be a great way to avoid hardcoded URLs in front. Also, params can be added to the URL as the front does not need them (so we can drop them from config sent to front).

Note: do not forget group items and hydrated ones.

```js
{
  columns: 4,
  tiles: [
    {
      type: 'ping',
      url: 'http://domain.tld:port/api/.../ping?param1&param2'
    }
  ]
}
```

**Comment by jsdidierlaurent** [comment]
Done
https://github.com/monitoror/monitoror/pull/50/commits/2be542ff9744fd2386c228013e48d5c317a62cef
