### ISSUE TITLE
Add Azure DevOps support

### ISSUE THREAD

**Issue by jsdidierlaurent** [monitoror/monitoror#73]
https://github.com/microsoft/azure-devops-go-api

**Comment by Lyyy** [comment]
Actually this project support Azure DevOps / VSTS : https://github.com/marcells/node-build-monitor (I forked the project to custom the view and to get closer for the Monitoror old look : https://github.com/Lyyy/node-build-monitor )

There are pipelines, which can be split into jobs, each job running on separate agent.
There are also release pipeline, that takes a classic pipeline artifact, and deploy it. The release pipeline is composed with a stage graph, each stage connected through a trigger or a manuel process.

**Comment by Lyyy** [comment]
Thank you! :)
